function [fitresult, gof] = ball_wedge_amp_fit_barsch(time_at_peaks, amplitude)
%CREATEFIT1(TIME_AT_PEAKS,AMPLITUDE)
%  Create a fit.
%
%  Data for 'Ball_wedge_amp_fit_barsch' fit:
%      X Input : time_at_peaks
%      Y Output: amplitude
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Nov-2020 16:09:28


%% Fit: 'Ball_wedge_amp_fit_barsch'.
[xData, yData] = prepareCurveData( time_at_peaks, amplitude );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [170699.903968442 -0.542983198110349];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Ball_wedge_amp_fit_barsch' );
h = plot( fitresult, xData, yData );
legend( h, 'Actual', 'Modelled', 'Location', 'NorthEast', 'Interpreter', 'none','FontSize', 16);
title("Ball Amplitude Profile for a Wedge Shot using an Exponential Fit.",'FontSize', 16);
% Label axes
xlabel( 'Time(s)', 'Interpreter', 'none','FontSize', 16);
ylabel( 'Amplitude', 'Interpreter', 'none','FontSize', 16);
grid on


