function [fitresult, gof] = Ball_Driver_vel_fit(time_at_peaks, vel_at_peaks)
%CREATEFIT1(TIME_AT_PEAKS,VEL_AT_PEAKS)
%  Create a fit.
%
%  Data for 'Ball_Driver_vel_fit' fit:
%      X Input : time_at_peaks
%      Y Output: vel_at_peaks
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Nov-2020 09:39:21


%% Fit: 'Ball_Driver_vel_fit'.
[xData, yData] = prepareCurveData( time_at_peaks, vel_at_peaks );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Ball_Driver_vel_fit' );
h = plot( fitresult, xData, yData );
title("Ball Velocity Profile for a Driver",'FontSize', 16);
legend( h, 'Actual', 'Modelled', 'Location', 'NorthEast', 'Interpreter', 'none' ,'FontSize', 16);
% Label axes
xlabel( 'Time (s)', 'Interpreter', 'none' ,'FontSize', 16);
ylabel( 'Velocity (m/s)', 'Interpreter', 'none' ,'FontSize', 16);
grid on


