function [fitresult, gof] = club_7_iron_amp_fit(time_at_peaks, amplitude)
%CREATEFIT1(TIME_AT_PEAKS,AMPLITUDE)
%  Create a fit.
%
%  Data for 'Club_7_iron_amp_fit' fit:
%      X Input : time_at_peaks
%      Y Output: amplitude
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Oct-2020 21:01:10


%% Fit: 'Club_7_iron_amp_fit'.
[xData, yData] = prepareCurveData( time_at_peaks, amplitude );

% Set up fittype and options.
ft = fittype( 'poly6' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Club_7_iron_amp_fit' );
h = plot( fitresult, xData, yData );
title("Amplitude Profile of 7 Iron Downswing",'FontSize',14);
legend( h, 'Actual', 'Model', 'Location', 'SouthEast', 'Interpreter', 'none','FontSize',14);
% Label axes
xlabel( 'Time (s)', 'Interpreter', 'none','FontSize',14);
ylabel( 'Amplitude', 'Interpreter', 'none','FontSize',14);
grid on


